src/main/assembly/dist/docs/examples/ddm/example1.xml
now the example will validate with the most recent XSDs
=> EASY-990 EASY970 upgraded example1 to latest narcis-types.xsd

src/main/assembly/dist/docs/examples/ddm/example1.xml, src/main/assembly/dist/docs/examples/ddm/example2.xml, src/main/assembly/dist/md/2016/ddm.xsd
Like the previous pull request mutually dependent with http://gerrit.dans.knaw.nl/#/c/854/
=> added streaming surrogate relation to DDM

src/main/assembly/dist/docs/examples/ddm/example2.xml
Could not reproduce the problem but cleaned up the comments in the DDM example about what works and what doesn't.
=> Jira issue EASY-995: a no-op sword deposit is accepted but a real one not

src/main/assembly/dist/docs/sword-v1-packaging.html
=> fixed a broken link

src/main/assembly/dist/docs/examples/ddm/example2.xml
N.B: Schema changes and validations make easy-schema and ddm mutualy(!) dependent. So ddm build will break until updated too.
=> EASY-1017 allow Envelope in dcx-gml:spatial (phase 2)

src/main/assembly/dist/property-list/2012/11/audience.xml, src/main/assembly/dist/property-list/audience.xml
fixes EASY-1079
* Add audience.xml to the easy-schema module
=> Add audience.xml to the schema module (EASY-1079)

.travis.yml, README.md
fixes EASY-1108
* describe maintenance of DDM-EMD documentation
Not much to choose from.
Follow the added description. If the generated packaging document shows differences, these updates should be fixed or committed.
=> EASY-1108 ddm-emd mapping

pom.xml, src/main/assembly/dist/md/2017/04/ddm.xsd, src/main/assembly/dist/md/2017/08/ddm.xsd, src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
=> Temp schema change

pom.xml, src/main/assembly/dist/bag/metadata/files/2017/09/files.xsd, src/main/assembly/dist/bag/metadata/files/files.xsd
Here are some more links that need referring to a hardcoded version of dublincore
=> hardcoded dublincore links

src/main/assembly/dist/docs/examples/dcx-gml/example1.xml, src/main/assembly/dist/docs/examples/ddm/example1.xml, src/main/assembly/dist/docs/examples/ddm/example2.xml
@janvanmansum @lindareijnhoudt I'm sorry, but can you do another release? Forgot some stuff... Found it while implementing the crosswalker. Please merge/release this one first before doing https://github.com/DANS-KNAW/easy-emd/pull/6.
=> fix schemas and expand with extra interior for good measure

src/main/assembly/dist/dcx/2017/09/dcx-dai.xsd, src/main/assembly/dist/docs/examples/dcx-dai/example1.xml, src/main/assembly/dist/docs/examples/ddm/example1.xml, src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd, src/main/assembly/dist/md/emd/2017/09/eas.xsd, src/main/assembly/dist/md/emd/2017/09/emd.xsd
part of EASY-1330
* add `dcx-dai:role` to `dcx-dai.xsd`
* change references in `ddm.xsd`
* add extra examples
* add the `role` to the EMD scheme
@lindareijnhoudt or @janvanmansum can you review this ASAP and publish the scheme?
=> EASY-1330 add role to creator/contributor

src/main/assembly/dist/md/emd/2017/09/eas.xsd
=> restrict role input to datacite values in EMD

src/main/assembly/dist/md/emd/2017/09/eas.xsd
=> fix broken scheme

src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd, src/main/assembly/dist/vocab/2017/09/identifier-type.xsd
part of EASY-1363
* add the eDNA-project identifier
=> EASY-1363: add eDNA-project identifier

src/main/assembly/dist/bag/metadata/amd/2012/amd.xsd, src/main/assembly/dist/bag/metadata/amd/2012/wfs.xsd, src/main/assembly/dist/bag/metadata/amd/2018/02/amd.xsd, src/main/assembly/dist/bag/metadata/amd/2018/02/wfs.xsd
NO EASY
* Rename the directories to adhere to the year/month template
* 
*
=> Put AMD schema's in appropriately named directories

src/main/assembly/dist/dcx/2018/03/dcx-dai.xsd, src/main/assembly/dist/md/2018/03/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
accompanies EASY-1486
* Clarify the comments
* 
*
=> EASY-1486: Clarify the comments

pom.xml, src/main/assembly/dist/bag/metadata/agreements/2018/05/agreements.xsd
=> dependency version bump

src/main/assembly/dist/property-list/2019/01/audience.xml, src/main/assembly/dist/property-list/audience.xml, src/main/assembly/dist/vocab/2019/01/narcis-type.xsd, src/main/assembly/dist/vocab/narcis-type.xsd
fixes EASY-1874 & EASY-1840
* EASY-1874: Change the easy-discipline identifiers to reflect the status quo in Fedora
* EASY-1840: Change label of D21300 to 'Biochemistry, molecular biology'
=> Change in audience.xml and narcis-type.xml

src/main/assembly/dist/bag/metadata/amd/amd.xsd, src/main/assembly/dist/bag/metadata/amd/wfs.xsd, src/main/assembly/dist/dcx/dcx-dai.xsd, src/main/assembly/dist/dcx/dcx-gml.xsd
Necessary for EASY-1943
https://github.com/DANS-KNAW/dans-bagit-profile/pull/1
=> EASY-1943 Added latest-version xsd copies for amd, wsf, dai and gml

src/main/assembly/dist/extern/springfield-actions.xsd
accompanies EASY-2040
there are no example xml's in easy-schema-examples for this xsd
=>  EASY-2040: Make springfield-actions namespace a URI

lib/src/main/resources/vocab/2020/identifier-type.xsd, lib/src/main/resources/vocab/identifier-type.xsd
fixes EASY-87
* Revert EDNA-PROJECT to eDNA-project, as it was named in 2017/09
* 
* 
=> EASY-2787: Revert EDNA-PROJECT to eDNA-project

lib/src/main/resources/bag/metadata/amd/2022/06/amd.xsd, lib/src/main/resources/bag/metadata/amd/amd.xsd
=> Use http instead of https for the schema location

lib/src/main/resources/dcx/2022/06/dcx-dai.xsd, lib/src/main/resources/dcx/dcx-dai.xsd
=> Clean up: Remove unused ORCIDType, ISNIType
