pom.xml, src/main/assembly/bin.xml
Fixed problem with base directory of easy-schema. The default configured in dans-prototype is to create a base directory in the tar.gz file that includes the version number e.g., easy-schema-1.x-SNAPSHOT. This is what we usually want, because it makes deploying multiple versions of a module alongside each other easier. For easy-schema we do not want this, because it makes both deploying it to the production maven repo AND using it as a testing dependency harder. The solution turned out to be a simple change to the assembly descriptor.
@lindareijnhoudt @jo-pol @ekoi @rvanheest @PaulBoon  for review.
=> Fix packaging of easy schema

README.md
Not sure the readme is the proper location, but at least it is a start. I followed my own instructions and it appears that the second example is rejected. I suppose because the schema's on https://easy.dans.knaw.nl/schemas/ are used and not the [maven-repo](http://maven-repo.dans.knaw.nl/webapp/search/artifact/?0&q=easy-schema) so we have to fix a dependency-issue.
=> Instructions for round trip test of DDM with sword-V1

README.md, src/main/assembly/dist/docs/sword-v1-packaging.html
Created a web page referred to by the sword-v1 [service document](https://easy.dans.knaw.nl/sword/servicedocument). When released this new page will appear on https://easy.dans.knaw.nl/schemas/docs/
Once we have consensus about the name and location of the new page and the change is merged and pushed to our maven repository, I can extend the tests in DDM to ensure that not only the examples are up to date with the ddm.xsd, but also this new page.
=> EASY-1032 sword-v1 DDM user documentatie

src/main/assembly/dist/dcx/2016/dcx-gml.xsd, src/main/assembly/dist/docs/examples/ddm/example2.xml
Only when the new XSD is available at https://easy.dans.knaw.nl/schemas/index.xml I can activate the new example and officially check its validity with the tests in the legacy ddm project.
=> EASY-1017 allow Envelope in dcx-gml:spatial (phase 1)

src/main/assembly/dist/md/emd/2016/eas.xsd, src/main/assembly/dist/md/emd/2016/emd.xsd, src/main/assembly/dist/md/emd/2016/qdc.xsd, src/main/assembly/dist/md/emd/2016/sdc.xsd, src/main/assembly/dist/md/emd/2016/xml.xsd
fixes EASY-1132
* allow `ALL_DISCIPLINES` as metadata format for new datasets deposited with the merged deposit form
<emd:other>
<eas:application-specific>
<eas:metadataformat>ALL_DISCIPLINES</eas:metadataformat>
<eas:pakbon-status>NOT_IMPORTED</eas:pakbon-status>
</eas:application-specific>
<eas:etc/>
</emd:other>
* provide annotations explaining the values for `<eas:metadataformat>`
*
Checkout and manually compare the new `src/main/assembly/dist/md/emd/2016/eas.xsd` with the old `src/main/assembly/dist/md/emd/2013/11/eas.xsd`
Create an emd.xml using auto-completion for  `<eas:metadataformat>`.
Note that we can only [hint humans](http://stackoverflow.com/questions/1950075/mark-element-as-deprecated-in-xsd#1950157) about the deprecation
repo                       | PR | note …
=> EASY-1132 merge deposit formats

src/main/assembly/dist/md/emd/eas.xsd, src/main/assembly/dist/md/emd/emd.xsd, src/main/assembly/dist/md/emd/qdc.xsd, src/main/assembly/dist/md/emd/sdc.xsd, src/main/assembly/dist/md/emd/xml.xsd
no JIRA ISSUE
* Place the EMD xsd's in the top directory. The latest version of the xsd will reside both here, and in the appropriate child directory.
Please refer to the latest version of an xsd schema using the URL _without_ the year-version path by default. only when there is a need to refer to an older version should you use the URL with the year-version path
Please note: this pattern will be used for the other schema-dirs as well. (as is already the case for the property-list/audience.xsd)
=> Place the EMD xsd's in the top directory.

README.md
improves documentation of the maintenance procedure
* help analysing EASY-1105, EASY-1108, EASY-1124
* 
* 
`easy-ingest-flow` might serve as an alternative for the round-trip test, it would not require access to the legacy code.
To document the expected result for external users, we might consider to add the resulting EMD, csv export, license document and safari-pdf-dump of the description tab. Depending on the deposit form definitions the description tab might show less than the XML/CSV export of the EMD resulting from a sword-v1 import of a DDM. 
Follow the described procedure. 
=> EASY-1105-1108-1124 maintenance documentation

src/main/assembly/dist/docs/sword-v1-packaging.html
fixes EASY-
* have a sword-v1-packaging page with the same help texts as on production
* no longer have the off-topic search articles
* 
Currently [published](https://easy.dans.knaw.nl/schemas/docs/sword-v1-packaging.html) version.
The new one printed at 48% so the tail of mapping table doesn't get lost: [Sword Packaging for EASY Sword-v1.pdf](https://github.com/DANS-KNAW/easy-schema/files/723323/Sword.Packaging.for.EASY.Sword-v1.pdf)
* The editable texts from the code base are installed in `/opt/easy-webui/res/example/editable/`
* The location of the actual values managed by the archivists are configured in the file `/opt/easy-webui/cfg/applications.properties` with the key `easy.editable.content.root`
* Compare these folders recursively.
* Changes should be copied from production to …
=> editable texts where behind for access-rights and audience

pom.xml, src/main/assembly/bin.xml, src/main/assembly/dist/md/2017/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd, src/test/scala/nl/knaw/dans/easy/schema/DDM2EMDSpec.scala, src/test/scala/nl/knaw/dans/easy/schema/PackagingSpec.scala
fixes EASY-1238
* Remove the ddm:relation from the ddm:profile
* Make ddm:available date required
* Import the ABR namespace
* Correct the inceptionYear in the pom and update ddm to version 3.0
* Update the license headers
* Import the correct dcx-gml
=> EASY-1238: fix some validation errors

src/main/assembly/dist/md/emd/2017/eas.xsd, src/main/assembly/dist/md/emd/2017/emd.xsd, src/main/assembly/dist/md/emd/2017/qdc.xsd, src/main/assembly/dist/md/emd/2017/sdc.xsd, src/main/assembly/dist/md/emd/2017/xml.xsd, src/main/assembly/dist/md/emd/eas.xsd
fixes EASY-1311
* Add 'archive' element to the 'applicationspecific' element in the emd. This 'archive' element has a 'location' attribute, indicating where the data and metadata is archived.
src/main/assembly/dist/md/emd/2017/eas.xsd
application-specific, archivelocation, archivetype
=> EASY-1311: Add 'archive' element to the 'applicationspecific' element

pom.xml, src/main/assembly/dist/extern/springfield-actions.xsd
NO-EASY
* Add the springfield schema as an external schema
* Remove the xml-schema-1.1 specific stuff from springfield-actions
* Exclude external schemas from getting a DANS license header
=> Add springfield-actions.xsd as an external schema

pom.xml
The RPM tried to set the owner and group of all the files to `easy-schema`. This led to a warning, as this user and group do not exist. This behaviour was inherited from `dans-parent` and does make sense for services, that have their own sysem user. Fixed the problem by overriding the rpm config to set the user/group to root/root.
=> Fix rpm user/group

src/main/assembly/dist/bag/metadata/files/2017/09/files.xsd, src/main/assembly/dist/bag/metadata/files/files.xsd
XML 1.1 validation doesn't work in easy-ingest-flow, so we revert this back to a 1.0 scheme
=> XML 1.1 to 1.0

src/main/assembly/dist/docs/examples/ddm/example1.xml, src/main/assembly/dist/docs/examples/ddm/example2.xml, src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
fixes EASY-1356
* make all relations be non-empty in ddm
* update the ddm-examples accordingly
repo                       | PR | notes
------------ | -------------|---
easy-split-multi-deposit                      | [PR#93](https://github.com/DANS-KNAW/easy-split-multi-deposit/pull/93) | although not required, they are related
=> EASY-1356: make relations non-empty tags in ddm

src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
related to EASY-1360
* Document restrictions on the use of dc(terms):license
* 
* 
easy-stage-dataset                      | [PR#125](https://github.com/DANS-KNAW/easy-stage-dataset/pull/125)
=> Document license restrictions in ddm

src/main/assembly/dist/docs/examples/ddm/example1.xml, src/main/assembly/dist/md/2017/09/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
fixes EASY-1374
* add the definition for `ddm:subject` to the DDM
* I have taken the liberty to add this to `2017-09` rather than making a new `2017-10`, since this (a) saves a couple extra PRs and (b) `2017-09` has not been taken into public use.
* apply some accidental formatting
* add an example for `ddm:subject`
@lindareijnhoudt please review, merge, publish on easy01, release on artifactory and let me know the new version number on artifactory (probably 1.15.0?); thanks!
=> EASY-1374: ddm:subject in ddm scheme

pom.xml
fixes EASY-1413
* upgrade the parent to 1.64
=> EASY-1413: upgrade to Scala 2.12

src/main/assembly/dist/bag/metadata/files/2018/02/files.xsd, src/main/assembly/dist/bag/metadata/files/2018/files.xsd
fixes EASY-1456
* Add additional-metadata element to files.xsd
with this new version, the following xml snippet should be valid:
<file filepath="data/path/to/a/random/sound/chicken.mp3">
<dcterms:format>audio/mpeg</dcterms:format>
<additional-metadata>
<addmd:properties/>
<addmd:additional id="addi" label="filemetadata">
<content>
<file_category>Audio</file_category>
<original_file>chicken.avi</original_file>
<file_content>Shrill sound</file_content>
<file_name>chicken.mp3</file_name>
<software>ffmpeg</software>
</content>
</addmd:additional>
</additional-metadata>
</file>
=> EASY-1456: Add additional-metadata element to files.xsd

src/main/assembly/dist/bag/metadata/amd/v0.1/amd.xsd, src/main/assembly/dist/bag/metadata/amd/v0.1/wfs.xsd, src/main/assembly/dist/bag/metadata/amd/v1.0/amd.xsd, src/main/assembly/dist/bag/metadata/amd/v1.0/wfs.xsd
fixes EASY-1457
* retro specify amd.xsd and wfs.xsd as v0.1
* add amd.xsd and wfs.xsd v1.0 
WFS: Changes from v0.1 to v1.0:
* Delete: Time spent is no longer recorded
* Add: revisionID
AMD: Changes from v0.1 to v1.0:
* delete: groupIds in the amd
* delete: datasetState/previousState no longer recorded, as state is not a property to be archived
* delete: stateChangeDates
* add: accessGranterId (TODO: better name)
=> EASY-1457: Specify amd.xsd

src/main/assembly/dist/md/2018/02/ddm.xsd
fixes EASY-1474
* Add ddm:temporal, analogue to ddm:subject
the following xml snippet should validate in a ddm.xml:
`<ddm:temporal subjectScheme="Archeologisch Basis Register" schemeURI="https://data.cultureelerfgoed.nl/term/id/abr/b6df7840-67bf-48bd-aa56-7ee39435d2ed" valueURI="https://data.cultureelerfgoed.nl/term/id/abr/697d935b-1d84-4145-86ce-1dcd2185a705" xml:lang="nld">Recent</ddm:temporal>
`
easy-ddm                      | [PR#22](https://github.com/DANS-KNAW/easy-ddm/pull/22)
=> EASY-1474: Add ddm:temporal in 2018/02/ddm.xsd

pom.xml
When migrating to the new parent pom, some configuration was lost:
* The resources-element that puts the filtered version-file at target/version/version
* Attaching the RPM plugin to the build
=> NO JIRA Fixed problem with version file.

src/main/assembly/dist/bag/metadata/agreements/2018/05/agreements.xsd, src/main/assembly/dist/bag/metadata/agreements/2018/12/agreements.xsd, src/main/assembly/dist/bag/metadata/agreements/2019/01/agreements.xsd, src/main/assembly/dist/bag/metadata/agreements/agreements.xsd, src/main/assembly/dist/bag/metadata/files/2017/09/files.xsd, src/main/assembly/dist/bag/metadata/files/2018/02/files.xsd, src/main/assembly/dist/bag/metadata/files/2018/04/files.xsd, src/main/assembly/dist/bag/metadata/files/files.xsd, src/main/assembly/dist/dcx/2012/10/dcx-dai.xsd, src/main/assembly/dist/dcx/2012/10/dcx-gml.xsd, src/main/assembly/dist/dcx/2012/10/dcx.xsd, src/main/assembly/dist/dcx/2016/dcx-gml.xsd, src/main/assembly/dist/dcx/2017/09/dcx-dai.xsd, src/main/assembly/dist/dcx/2018/03/dcx-dai.xsd, src/main/assembly/dist/dcx/2019/01/dcx-dai.xsd, src/main/assembly/dist/dcx/dcx-dai.xsd, src/main/assembly/dist/dcx/dcx-gml.xsd, src/main/assembly/dist/md/2012/10/ddm.xsd, src/main/assembly/dist/md/2012/11/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd, src/main/assembly/dist/vocab/2012/10/abr-type.xsd, src/main/assembly/dist/vocab/2012/10/narcis-type.xsd, src/main/assembly/dist/vocab/2012/abr-type.xsd, src/main/assembly/dist/vocab/2015/narcis-type.xsd, src/main/assembly/dist/vocab/2017/09/identifier-type.xsd, src/main/assembly/dist/vocab/2017/identifier-type.xsd, src/main/assembly/dist/vocab/2019/01/narcis-type.xsd, src/main/assembly/dist/vocab/narcis-type.xsd
EASY-2240
* Update http to https to avoid 301 Moved Permanently
Since this redirection will break validation as the SaxParser does not seem to follow the 301
easy-ddm                      | [PR#](PRlink)
=> EASY-2240: Update http to https for dublincore to avoid 301 Moved Permanently

src/main/assembly/dist/md/2019/07/ddm.xsd, src/main/assembly/dist/md/ddm/ddm.xsd
fixes EASY-2205
* Allow scheme attribute on all ddm:relationTypes
The values are restricted to a regex pattern. the Streaming-surrogate-relation is still allowed on ddm:relation. However it is now allowed on all other relation-types too, though it should not be used there.
The values allowed can be expressed with or without a namespace-like prefix. However, this is not really a namespace as it is part of a string. 
I do not know a better way to do this. I've updated the examples too, to show what i wanted to achieve with this change. It is designed to be backwards compatible, so all previously accepted ddm files should still validate
easy-schema-examples                      | …
=> EASY-2205: Allow scheme attribute on all ddm:relationTypes

lib/src/main/resources/md/2020/03/ddm.xsd
fixes EASY-2674
fixes mistake made in #82 
* copy `ddm.xsd` from `2020/03/23/ddm.xsd` to `2020/03/ddm.xsd` to ensure backwards compatibility
=> EASY-2674: copy ddm.xsd from 2020/03/23/ddm.xsd to 2020/03/ddm.xsd to ensure backwards compatibility

lib/src/main/resources/vocab/2020/identifier-type.xsd, lib/src/main/resources/vocab/identifier-type.xsd
fixes EASY-2787
* Allow both EDNA-PROJECT as eDNA-project as id-type
* 
* 
=> EASY-2787: Allow both EDNA-PROJECT as eDNA-project as id-type

lib/src/main/resources/bag/metadata/afm/2020/10/afm.xsd, lib/src/main/resources/bag/metadata/afm/afm.xsd, lib/src/main/resources/bag/metadata/agreements/2021/11/agreements.xsd, lib/src/main/resources/bag/metadata/agreements/agreements.xsd, lib/src/main/resources/bag/metadata/files/2020/06/files.xsd, lib/src/main/resources/bag/metadata/files/files.xsd, lib/src/main/resources/bag/metadata/prov/2021/provenance.xsd, lib/src/main/resources/bag/metadata/prov/provenance.xsd, lib/src/main/resources/collections/oai-dc.xsd, lib/src/main/resources/dcx/2020/03/dcx-dai.xsd, lib/src/main/resources/dcx/dcx-dai.xsd, lib/src/main/resources/dcx/dcx-gml.xsd, lib/src/main/resources/extern/dc.xsd, lib/src/main/resources/extern/dcmitype.xsd, lib/src/main/resources/extern/dcterms.xsd, lib/src/main/resources/md/2022/01/ddm.xsd, lib/src/main/resources/md/ddm/ddm.xsd, lib/src/main/resources/vocab/2021/03/identifier-type.xsd, lib/src/main/resources/vocab/identifier-type.xsd, lib/src/main/resources/vocab/narcis-type.xsd
fixes DD-832
* Add `dc.xsd`, `dcterms.xsd` and `dcmitype.xsd` into `extern` directory
* replace all `dublincore schema location` references to point to this directory
=> DD-832: Put DC schema's in the 'extern' directory of easy-schema

lib/src/main/resources/bag/metadata/amd/2022/02/amd.xsd, lib/src/main/resources/bag/metadata/amd/amd.xsd, lib/src/main/resources/bag/metadata/prov/2022/02/provenance.xsd, lib/src/main/resources/bag/metadata/prov/provenance.xsd
fixes DD-811
* Add filename attribute to prov:file element (provenance.xsd)
* Add stateChangeDate element to ContentType (provenance.xsd)
* Add encoding element to ContentType (provenance.xsd)
* reintroduce: stateChangeDate (amd.xsd)
* Allow changeDate in stateChangeDate to be empty (amd.xsd)
easy-convert-bag-to-deposit                      | [PR#79](https://github.com/DANS-KNAW/easy-convert-bag-to-deposit/pull/79)
=> DD-811: Add encoding element to ContentType
